### ISSUE TITLE
Unresolved Dependencies

### ISSUE THREAD

**Issue by timjstewart** [scalatra/scalatra.g8#44]
Environment: Mac OS X (v10.10.2)

% java -version 
java version "1.8.0_25"
Java(TM) SE Runtime Environment (build 1.8.0_25-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.25-b02, mixed mode)

% sbt --version  
sbt launcher version 0.13.8

% g8 scalatra/scalatra-sbt                    # I just picked all the defaults...
organization [com.example]: 
name [My Scalatra Web App]: 
version [0.1.0-SNAPSHOT]: 
servlet_name [MyScalatraServlet]: 
package [com.example.app]: 
scala_version [2.11.6]: 
sbt_version [0.13.8]: 
scalatra_version [maven(org.scalatra, scalatra_2.11)]: 

Template applied in ./my-scalatra-web-app

% cd my-scalatra-web-app                                                                                                                                                            

% sbt                                                                                                                                                           ~/my-scalatra-web-app

[info] Loading global plugins from /Users/stewtj3/.sbt/0.13/plugins
[info] Loading project definition from /Users/stewtj3/my-scalatra-web-app/project
[info] Updating {file:/Users/stewtj3/my-scalatra-web-app/project/}my-scalatra-web-app-build...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
[info] Compiling 1 Scala source to /Users/stewtj3/my-scalatra-web-app/project/target/scala-2.10/sbt-0.13/classes...
[info] Set current project to My Scalatra Web App (in build file:/Users/stewtj3/my-scalatra-web-app/)
[info] Updating {file:/Users/stewtj3/my-scalatra-web-app/}my-scalatra-web-app...
[info] Resolving org.scalatra#scalatra_2.11;maven(org.scalatra, scalatra_2.11) ...
[warn]  module not found: org.scalatra#scalatra_2.11;maven(org.scalatra, scalatra_2.11)
[warn] ==== local: tried
[warn]   /Users/stewtj3/.ivy2/local/org.scalatra/scalatra_2.11/maven(org.scalatra, scalatra_2.11)/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/org/scalatra/scalatra_2.11/maven(org.scalatra, scalatra_2.11)/scalatra_2.11-maven(org.scalatra, scalatra_2.11).pom
[warn] ==== typesafe-ivy-releases: tried
[warn]   https://repo.typesafe.com/typesafe/ivy-releases/org.scalatra/scalatra_2.11/maven(org.scalatra, scalatra_2.11)/ivys/ivy.xml
[warn] ==== Scalaz Bintray Repo: tried
[warn]   http://dl.bintray.com/scalaz/releases/org/scalatra/scalatra_2.11/maven(org.scalatra, scalatra_2.11)/scalatra_2.11-maven(org.scalatra, scalatra_2.11).pom
[info] Resolving org.scalatra#scalatra-scalate_2.11;maven(org.scalatra, scalatra_2.11) ...
[warn]  module not found: org.scalatra#scalatra-scalate_2.11;maven(org.scalatra, scalatra_2.11)
[warn] ==== local: tried
[warn]   /Users/stewtj3/.ivy2/local/org.scalatra/scalatra-scalate_2.11/maven(org.scalatra, scalatra_2.11)/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/org/scalatra/scalatra-scalate_2.11/maven(org.scalatra, scalatra_2.11)/scalatra-scalate_2.11-maven(org.scalatra, scalatra_2.11).pom
[warn] ==== typesafe-ivy-releases: tried
[warn]   https://repo.typesafe.com/typesafe/ivy-releases/org.scalatra/scalatra-scalate_2.11/maven(org.scalatra, scalatra_2.11)/ivys/ivy.xml
[warn] ==== Scalaz Bintray Repo: tried
[warn]   http://dl.bintray.com/scalaz/releases/org/scalatra/scalatra-scalate_2.11/maven(org.scalatra, scalatra_2.11)/scalatra-scalate_2.11-maven(org.scalatra, scalatra_2.11).pom
[info] Resolving org.scalatra#scalatra-specs2_2.11;maven(org.scalatra, scalatra_2.11) ...
[warn]  module not found: org.scalatra#scalatra-specs2_2.11;maven(org.scalatra, scalatra_2.11)
[warn] ==== local: tried
[warn]   /Users/stewtj3/.ivy2/local/org.scalatra/scalatra-specs2_2.11/maven(org.scalatra, scalatra_2.11)/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/org/scalatra/scalatra-specs2_2.11/maven(org.scalatra, scalatra_2.11)/scalatra-specs2_2.11-maven(org.scalatra, scalatra_2.11).pom
[warn] ==== typesafe-ivy-releases: tried
[warn]   https://repo.typesafe.com/typesafe/ivy-releases/org.scalatra/scalatra-specs2_2.11/maven(org.scalatra, scalatra_2.11)/ivys/ivy.xml
[warn] ==== Scalaz Bintray Repo: tried
[warn]   http://dl.bintray.com/scalaz/releases/org/scalatra/scalatra-specs2_2.11/maven(org.scalatra, scalatra_2.11)/scalatra-specs2_2.11-maven(org.scalatra, scalatra_2.11).pom
[info] Resolving org.scala-lang#scala-reflect;2.11.0 ...
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: org.scalatra#scalatra_2.11;maven(org.scalatra, scalatra_2.11): not found
[warn]  :: org.scalatra#scalatra-scalate_2.11;maven(org.scalatra, scalatra_2.11): not found
[warn]  :: org.scalatra#scalatra-specs2_2.11;maven(org.scalatra, scalatra_2.11): not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn]  Note: Unresolved dependencies path:
[warn]      org.scalatra:scalatra_2.11:maven(org.scalatra, scalatra_2.11) (/Users/stewtj3/my-scalatra-web-app/project/build.scala#L25)
[warn]        +- com.example:my-scalatra-web-app_2.11:0.1.0-SNAPSHOT
[warn]      org.scalatra:scalatra-scalate_2.11:maven(org.scalatra, scalatra_2.11) (/Users/stewtj3/my-scalatra-web-app/project/build.scala#L25)
[warn]        +- com.example:my-scalatra-web-app_2.11:0.1.0-SNAPSHOT
[warn]      org.scalatra:scalatra-specs2_2.11:maven(org.scalatra, scalatra_2.11) (/Users/stewtj3/my-scalatra-web-app/project/build.scala#L25)
[warn]        +- com.example:my-scalatra-web-app_2.11:0.1.0-SNAPSHOT
sbt.ResolveException: unresolved dependency: org.scalatra#scalatra_2.11;maven(org.scalatra, scalatra_2.11): not found
unresolved dependency: org.scalatra#scalatra-scalate_2.11;maven(org.scalatra, scalatra_2.11): not found
unresolved dependency: org.scalatra#scalatra-specs2_2.11;maven(org.scalatra, scalatra_2.11): not found
    at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:291)
    at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:188)
    at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:165)
    at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:155)
    at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:155)
    at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:132)
    at sbt.IvySbt.sbt$IvySbt$$action$1(Ivy.scala:57)
    at sbt.IvySbt$$anon$4.call(Ivy.scala:65)
    at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
    at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
    at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
    at xsbt.boot.Using$.withResource(Using.scala:10)
    at xsbt.boot.Using$.apply(Using.scala:9)
    at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
    at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
    at xsbt.boot.Locks$.apply0(Locks.scala:31)
    at xsbt.boot.Locks$.apply(Locks.scala:28)
    at sbt.IvySbt.withDefaultLogger(Ivy.scala:65)
    at sbt.IvySbt.withIvy(Ivy.scala:127)
    at sbt.IvySbt.withIvy(Ivy.scala:124)
    at sbt.IvySbt$Module.withModule(Ivy.scala:155)
    at sbt.IvyActions$.updateEither(IvyActions.scala:165)
    at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1369)
    at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1365)
    at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$87.apply(Defaults.scala:1399)
    at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$87.apply(Defaults.scala:1397)
    at sbt.Tracked$$anonfun$lastOutput$1.apply(Tracked.scala:37)
    at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1402)
    at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1396)
    at sbt.Tracked$$anonfun$inputChanged$1.apply(Tracked.scala:60)
    at sbt.Classpaths$.cachedUpdate(Defaults.scala:1419)
    at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1348)
    at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1310)
    at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
    at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
    at sbt.std.Transform$$anon$4.work(System.scala:63)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
    at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
    at sbt.Execute.work(Execute.scala:235)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
    at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
    at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
[error](*:update) sbt.ResolveException: unresolved dependency: org.scalatra#scalatra_2.11;maven(org.scalatra, scalatra_2.11): not found
[error] unresolved dependency: org.scalatra#scalatra-scalate_2.11;maven(org.scalatra, scalatra_2.11): not found
[error] unresolved dependency: org.scalatra#scalatra-specs2_2.11;maven(org.scalatra, scalatra_2.11): not found
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore?

**Comment by seratch** [comment]
Please use giter8 0.6.8 or higher.

**Comment by dozed** [comment]
This is due to https://github.com/scalatra/scalatra-sbt.g8/commit/288a6ca43760c2b30d3fa8f83884e4032f203c59#diff-d5b0299875acd07cbaec00b0114f8a1cL8. Do we need to enforce a specific giter8 version?

**Comment by seratch** [comment]
We noticed here for now. https://github.com/scalatra/scalatra-sbt.g8#use-this-template

I'm not sure it's possible but enforcing users a specific g8 version would be better.

**Comment by jboissard** [comment]
note that brew installs 0.6.6 by default - can be misleading

**Comment by bosr** [comment]
@jboissard: I've just submitted a PR to Homebrew for 0.6.8

**Comment by magnolia-k** [comment]
Currently this problem is solved.
